// ─── Learning: Stage 1 cards — Foundations ───────────────────
// Card keys must match curriculum.ts (Stage 1 · Foundations).
// Content rules: plain language, no gamification, concrete $ example on every card.

import type { LearningCard } from '@/lib/learning/triggers';

export const STAGE1_CARDS: Record<string, LearningCard> = {
  'stock': {
    term: 'Stock',
    headline: 'What is a Stock?',
    body: 'A stock is a share of ownership in a company. Buy one and you own a small slice of that business — its profits, its growth, and its risks. Stocks trade on exchanges, and their prices move every second the market is open.',
    example: 'Buying 1 share of a $50 stock makes you a part-owner of that company, however tiny your slice.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '📈', investopediaSlug: 's/stock',
  },
  'share': {
    term: 'Share',
    headline: 'What is a Share?',
    body: 'A share is a single unit of stock — the smallest piece of a company you can buy. Companies split ownership into millions of shares so many investors can each own a piece. "Stock" describes the whole thing; a share is one slice of it.',
    example: 'If a company has 10 million shares and you own 1,000, you own 0.01% of the business.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🍰',
  },
  'stock exchange': {
    term: 'Stock Exchange',
    headline: 'What is a Stock Exchange?',
    body: 'A stock exchange is a regulated marketplace where buyers and sellers meet to trade stocks. It matches orders, publishes prices, and enforces rules so trades settle fairly. The NYSE and Nasdaq are the big US ones — you never call the exchange, your broker routes your order there.',
    example: 'When you tap Buy on the order ticket, your broker sends that order to an exchange like Nasdaq to find a seller.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🏛️', investopediaSlug: 's/stockexchange',
  },
  'ticker symbol': {
    term: 'Ticker Symbol',
    headline: 'What is a Ticker Symbol?',
    body: 'A ticker symbol is the short code that identifies a stock — like AAPL for Apple. Every listed company gets one, usually one to four letters. You use it to look up a quote, place an order, or track a position, and it sits next to every row in your holdings.',
    example: 'Type "TSLA" into search and you pull up Tesla\'s live price instead of typing the full company name.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🔤', investopediaSlug: 't/tickersymbol',
  },
  'market hours': {
    term: 'Market Hours',
    headline: 'What are Market Hours?',
    body: 'Market hours are the fixed window when US stock exchanges are officially open: 9:30 a.m. to 4:00 p.m. Eastern, Monday through Friday. Outside that, regular trading stops, though limited after-hours sessions still run. Prices during the day are live; quotes after the close can be thin.',
    example: 'A 2 p.m. ET order on a Tuesday fills right away; the same order at midnight waits for the 9:30 a.m. open.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🕘',
  },
  'after-hours trading': {
    term: 'After-Hours Trading',
    headline: 'What is After-Hours Trading?',
    body: 'After-hours trading happens outside the regular 9:30–4:00 session, typically 4:00–8:00 p.m. Eastern. It exists so traders can react to earnings or news that breaks after the close. Volume is thinner and spreads are wider, so prices can swing hard on few trades — fills are less predictable.',
    example: 'A company beats earnings at 4:15 p.m. and the stock jumps 8% after hours on light volume before the next open.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🌙', investopediaSlug: 'a/afterhourstrading',
  },
  'index fund': {
    term: 'Index Fund',
    headline: 'What is an Index Fund?',
    body: 'An index fund is a fund built to track a market index, like the S&P 500, by holding all or most of the same stocks. Because it just mirrors the index it needs little management, so fees stay low. One purchase gives you broad, diversified exposure instead of betting on a single company.',
    example: 'A $1,000 S&P 500 index fund holds a tiny piece of 500 companies for a fee as low as 0.03% a year.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🧺', investopediaSlug: 'i/indexfund',
  },
  'mutual fund': {
    term: 'Mutual Fund',
    headline: 'What is a Mutual Fund?',
    body: 'A mutual fund pools money from many investors to buy a basket of stocks, bonds, or both. Professional managers run it, and you buy shares at the end-of-day price, not a live one. That makes them simple, but less flexible than ETFs that trade all day.',
    example: 'You put $500 into a fund holding 200 stocks; your money buys shares at that day\'s closing net asset value.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🤝', investopediaSlug: 'm/mutualfund',
  },
  'bond': {
    term: 'Bond',
    headline: 'What is a Bond?',
    body: 'A bond is a loan you make to a government or company. They pay you interest — the coupon — on a schedule and return your principal at maturity. Bonds are generally steadier than stocks, so they often balance a portfolio, but they still carry default and interest-rate risk.',
    example: 'A $1,000 5-year Treasury paying 4% sends you $40 a year, then your $1,000 back at maturity.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '📜', investopediaSlug: 'b/bond',
  },
  'REIT': {
    term: 'REIT',
    headline: 'What is a REIT?',
    body: 'A REIT — real estate investment trust — is a company that owns income-producing property like apartments, offices, or data centers. By law they pay out at least 90% of taxable income as dividends, so they are a way to own real estate without buying a building. They trade like stocks.',
    example: 'A $50 REIT share paying $3 a year in dividends gives you a 6% yield without a mortgage.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🏘️', investopediaSlug: 'r/reit',
  },
  'commodity': {
    term: 'Commodity',
    headline: 'What is a Commodity?',
    body: 'A commodity is a raw material — oil, gold, wheat, copper — traded in bulk. Commodities have no earnings or dividends; their price is pure supply and demand. Investors use them to hedge inflation or diversify, usually through futures or ETFs rather than holding the physical stuff.',
    example: 'One oil futures contract controls 1,000 barrels, so a $1 move in crude is a $1,000 swing.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🛢️', investopediaSlug: 'c/commodity',
  },
  'cash and money market': {
    term: 'Cash and Money Market',
    headline: 'Cash and Money Market Funds',
    body: 'Cash is uninvested dollars sitting in your account or a money market fund. Those funds hold short-term, low-risk debt and aim to keep a $1 share price while paying a small yield. They are where you park money you might need soon — not where you grow it.',
    example: 'Parking $5,000 in a money market fund at 5% earns about $250 a year while staying liquid.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🏦', investopediaSlug: 'm/moneymarket',
  },
  'limit order': {
    term: 'Limit Order',
    headline: 'What is a Limit Order?',
    body: 'A limit order sets the most you will pay to buy, or the least you will accept to sell. It only fills at your price or better, so you control the price but not the timing. If the market never reaches your number, the order just sits unfilled.',
    example: 'Stock is $52; you place a buy limit at $50 and it only fills if the price drops to $50 or lower.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🎯', investopediaSlug: 'l/limitorder',
  },
  'stop order': {
    term: 'Stop Order',
    headline: 'What is a Stop Order?',
    body: 'A stop order becomes a market order once the price hits a level you set. Traders use it to cap losses or lock in gains. The catch: once triggered, it fills at whatever the market gives, so in a fast drop you can get less than your stop price.',
    example: 'You own at $100 and set a stop at $90; if it trades there, the order triggers and sells at the next available price.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🛑', investopediaSlug: 's/stoporder',
  },
  'stop-limit order': {
    term: 'Stop-Limit Order',
    headline: 'Stop-Limit Order vs Stop Order',
    body: 'A stop-limit order combines both: when the stop price triggers, it places a limit order instead of a market order. That guarantees you never sell below your limit, but if the price gaps past it the order may not fill at all. You trade certainty of price for risk of no fill.',
    example: 'Stop at $90, limit at $88: once it hits $90 it sells, but never below $88 — and not at all if it gaps straight to $85.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🚧',
  },
  'time in force': {
    term: 'Time in Force',
    headline: 'What is Time in Force?',
    body: 'Time in force tells the broker how long an order stays live. Day orders expire at the close; GTC (good-til-canceled) orders stay open for weeks until filled or you cancel them. It matters most for limit orders that may sit away from the current price.',
    example: 'A GTC buy limit at $50 can sit for 60 days waiting for a dip, while a day order dies at 4:00 p.m.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '⏳', investopediaSlug: 't/timeinforce',
  },
  'fractional shares': {
    term: 'Fractional Shares',
    headline: 'What are Fractional Shares?',
    body: 'Fractional shares let you buy less than one full share of a stock. Instead of paying the full price, you buy a dollar amount and get a slice of a share. It makes expensive stocks accessible and lets every dollar in your account go to work.',
    example: 'You put $25 into a $1,000 stock and own 0.025 shares — a real slice, same price move.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🧩', investopediaSlug: 'f/fractionalshares',
  },
  'bid-ask spread': {
    term: 'Bid-Ask Spread',
    headline: 'What is the Bid-Ask Spread?',
    body: 'The bid is the highest price a buyer will pay; the ask is the lowest a seller will take. The gap between them is the spread — a hidden cost every time you trade. Tight spreads mean a liquid, easy-to-trade stock; wide spreads mean you pay more to get in and out.',
    example: 'Bid $99.90, ask $100.10 — you buy at $100.10 and would instantly sell at $99.90, a $0.20 cost per share.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '📏', investopediaSlug: 'b/bid-ask-spread',
  },
  'slippage': {
    term: 'Slippage',
    headline: 'What is Slippage?',
    body: 'Slippage is the difference between the price you expected and the price you actually got. It happens when the market moves between the moment you send an order and the moment it fills — worst in fast markets and thin stocks. Limit orders protect you from it; market orders don\'t.',
    example: 'You hit buy expecting $50.00 but the fill comes back at $50.35 — that $0.35 gap is slippage.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🎢', investopediaSlug: 's/slippage',
  },
  'price quote': {
    term: 'Price Quote',
    headline: 'What is a Price Quote?',
    body: 'A price quote is a snapshot of a stock right now: its latest trade price, the bid, the ask, and often the day\'s volume and change. It is the number behind every holding row and the starting point for any order. Quotes update in real time during market hours.',
    example: 'A quote showing 148.20 ▲1.35 means the last trade was $148.20, up $1.35 on the day.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🏷️',
  },
  'volume': {
    term: 'Volume',
    headline: 'What is Volume?',
    body: 'Volume is the number of shares traded over a period, usually the day. High volume means lots of interest and easy trading; low volume means thin liquidity and bigger price swings. Big moves on heavy volume tend to carry more weight than moves on light volume.',
    example: '10 million shares traded versus a 2 million average signals unusual attention — often news-driven.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🔊', investopediaSlug: 'v/volume',
  },
  '52-week range': {
    term: '52-Week Range',
    headline: 'What is the 52-Week Range?',
    body: 'The 52-week range shows the lowest and highest price a stock hit over the past year. It is a quick way to see where today\'s price sits — near the top, the bottom, or somewhere between. It is context, not a signal; a stock near its low isn\'t automatically cheap.',
    example: 'A range of $80–$150 with the stock at $142 means it is trading near its yearly high.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '↕️',
  },
  'settlement T+1': {
    term: 'Settlement (T+1)',
    headline: 'What is T+1 Settlement?',
    body: 'Settlement is when a trade is final — cash and shares officially change hands. Since 2024, US stocks settle one business day after the trade, called T+1. Until it settles the trade is pending; after, the shares show up in your holdings and the cash leaves your account.',
    example: 'Buy 10 shares on Monday and by Tuesday the shares are settled and the cash has left your account.',
    level: 'Apprentice', category: 'Foundations',
    emoji: '🗓️',
  },
};
