// ─── Learning: Stage 2 cards — Reading the Market ───
// Card keys must match curriculum.ts. Content rules: plain language, no gamification,
// concrete $ example on every card.

import type { LearningCard } from '@/lib/learning/triggers';

export const STAGE2_CARDS: Record<string, LearningCard> = {
  // ── Company fundamentals ───────────────────────────────────
  'revenue growth': {
    term: 'Revenue Growth',
    headline: 'What is Revenue Growth?',
    body: 'Revenue growth is how much a company\'s sales increased versus the same period a year earlier, shown as a percentage. It\'s the top line — every margin and profit figure is built on it. Consistent double-digit growth usually justifies a premium valuation; slowing growth often precedes a falling stock.',
    example: 'A company booked $1.2B in sales this year versus $1.0B last year → 20% revenue growth. Analysts expected 15%, so the stock jumped on the beat.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '💹',
  },
  'gross margin': {
    term: 'Gross Margin',
    headline: 'What is Gross Margin?',
    body: 'Gross margin is the percentage of revenue left after subtracting the direct cost of producing goods or services, known as cost of goods sold. It shows how efficiently a company turns sales into gross profit. Software firms often run 70%+, grocers near 25% — compare within an industry, not across it.',
    example: 'A retailer sells a jacket for $100 that cost $60 to buy → gross profit $40 → gross margin 40%. Raise the price to $110 and margin jumps to 45%.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🍰', investopediaSlug: 'g/grossmargin',
  },
  'operating margin': {
    term: 'Operating Margin',
    headline: 'What is Operating Margin?',
    body: 'Operating margin is operating profit — revenue minus all day-to-day costs like cost of goods, salaries, marketing, and R&D — divided by revenue. Unlike gross margin, it captures the full cost of running the business. It tells you how much of each sales dollar survives before interest and taxes.',
    example: 'Revenue $500M with operating costs of $425M → operating profit $75M → operating margin 15%. If costs creep to $450M, margin falls to 10% and the stock usually feels it.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '⚙️', investopediaSlug: 'o/operatingmargin',
  },
  'free cash flow': {
    term: 'Free Cash Flow',
    headline: 'What is Free Cash Flow?',
    body: 'Free cash flow is the cash a company generates after paying for the investments needed to keep running and growing, called capital expenditures. Unlike accounting profit, it\'s hard to fake — it\'s actual money in the bank. Companies use it to pay dividends, buy back stock, or pay down debt.',
    example: 'A company generates $2B from operations and spends $500M on equipment → free cash flow of $1.5B. It returns $600M to shareholders and keeps the rest.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '💧', investopediaSlug: 'f/freecashflow',
  },
  'debt-to-equity': {
    term: 'Debt-to-Equity',
    headline: 'What is Debt-to-Equity?',
    body: 'Debt-to-equity divides total debt by shareholders\' equity — how much the company borrows versus what owners actually own. A high ratio means heavy leverage: bigger swings in profit and more pain if rates rise. Capital-intensive sectors like utilities and banks run higher ratios than tech by design.',
    example: 'A company holds $800M of debt and $400M of equity → a D/E of 2.0. It\'s highly leveraged, so a rate hike bites harder than at a D/E of 0.4.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🏋️', investopediaSlug: 'd/debtequityratio',
  },
  'return on equity': {
    term: 'Return on Equity',
    headline: 'What is Return on Equity?',
    body: 'Return on equity (ROE) is net income divided by shareholders\' equity — how much profit a company squeezes from each dollar owners have invested. Consistently high ROE, say 15%+, suggests a strong, efficient business. But watch leverage: debt can inflate ROE without improving the underlying business.',
    example: 'A company earns $150M on $1B of shareholder equity → ROE of 15%. If it borrowed heavily to get there, check debt-to-equity before celebrating.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🪙', investopediaSlug: 'r/returnonequity',
  },
  'earnings guidance': {
    term: 'Earnings Guidance',
    headline: 'What is Earnings Guidance?',
    body: 'Earnings guidance is a company\'s own forecast of future revenue and profit, usually shared on the quarterly call and covering the next quarter or year. Analysts and algorithms trade on it. A solid quarter paired with lowered guidance can sink a stock — expectations matter more than the past.',
    example: 'A company beats estimates with $2.10 EPS but guides next quarter to $1.60 versus the $1.90 consensus. The stock drops 8% the next morning despite the beat.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🔮',
  },

  // ── The economy ────────────────────────────────────────────
  'interest rates': {
    term: 'Interest Rates',
    headline: 'What are Interest Rates?',
    body: 'Interest rates are the cost of borrowing money, set by central banks and priced by bond markets. When rates rise, borrowing gets expensive, future profits are discounted harder, and stocks — especially growth — tend to fall. Falling rates do the opposite. Rates are the gravity of asset prices.',
    example: 'A 30-year mortgage at 3% costs $421 a month per $100k borrowed; at 7% it\'s $665. Higher rates squeeze consumers and pressure stock valuations.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🎚️', investopediaSlug: 'i/interestrate',
  },
  'inflation': {
    term: 'Inflation',
    headline: 'What is Inflation?',
    body: 'Inflation is the rate at which prices for goods and services rise over time, eroding the purchasing power of your money. Central banks target around 2% a year. Too hot and rates rise to cool it; too cold and economies stall. It\'s why cash sitting under a mattress loses value.',
    example: 'At 4% inflation, $100 buys what $96 bought a year ago. Over 10 years, $1,000 of purchasing power melts to roughly $675.',
    level: 'Apprentice', category: 'Reading the Market',
    emoji: '🎈', investopediaSlug: 'i/inflation',
  },
  'consumer price index': {
    term: 'Consumer Price Index',
    headline: 'What is the Consumer Price Index?',
    body: 'The Consumer Price Index (CPI) tracks the average price change of a basket of everyday goods — food, housing, energy, transportation, medical care. Released monthly, it\'s the headline inflation number markets watch. A hot CPI print often triggers rate-hike fears and a bad day for stocks.',
    example: 'CPI comes in at 4.2% year-over-year versus 3.8% expected. Bond yields spike and tech stocks sell off, because the Fed may now keep rates higher for longer.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🛒', investopediaSlug: 'c/consumerpriceindex',
  },
  'federal reserve': {
    term: 'Federal Reserve',
    headline: 'What is the Federal Reserve?',
    body: 'The Federal Reserve is the central bank of the United States. It sets short-term interest rates and manages the money supply to pursue two goals: stable prices and maximum employment. Its decisions ripple through every asset class. You\'ll see Fed events flagged on this app\'s macro calendar.',
    example: 'The Fed raises its benchmark rate by 0.25% to 5.50%. Mortgage rates climb, the dollar strengthens, and rate-sensitive stocks like homebuilders drop.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🏛️',
  },
  'fomc meeting': {
    term: 'FOMC Meeting',
    headline: 'What is an FOMC Meeting?',
    body: 'The FOMC, or Federal Open Market Committee, is the Fed body that votes on interest rates. It meets roughly eight times a year; the decision lands at 2pm ET, followed by a press conference. These are the most anticipated dates on the economic calendar, and volatility around them runs high.',
    example: 'Before a March FOMC meeting, traders price a 70% chance of no change. The Fed holds but signals two cuts this year — stocks rally into the close.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🗓️',
  },
  'jobs report': {
    term: 'Jobs Report',
    headline: 'What is the Jobs Report?',
    body: 'The jobs report is the monthly U.S. employment release — officially the Employment Situation from the Bureau of Labor Statistics. It shows how many jobs were added, the unemployment rate, and wage growth. It moves markets because strong hiring can mean the Fed keeps rates high.',
    example: 'The economy adds 250,000 jobs versus 180,000 expected, and wages rise 4.5%. Bond yields jump as traders bet the Fed stays hawkish, and stocks slip.',
    level: 'Apprentice', category: 'Reading the Market',
    emoji: '👷',
  },
  'GDP': {
    term: 'GDP',
    headline: 'What is GDP?',
    body: 'Gross Domestic Product is the total value of everything a country produces — goods and services — over a period. It\'s the broadest scoreboard for an economy. Two consecutive quarters of decline is a common unofficial definition of recession. Markets track the growth rate, not the level.',
    example: 'U.S. GDP grows 2.8% annualized versus 2.0% expected. Cyclical stocks like industrials and banks rally on the stronger-than-expected economy.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🧮', investopediaSlug: 'g/gdp',
  },
  'recession': {
    term: 'Recession',
    headline: 'What is a Recession?',
    body: 'A recession is a significant, broad decline in economic activity lasting months — falling output, rising unemployment, weaker spending. The classic rule of thumb is two straight quarters of shrinking GDP. Stocks often bottom before the recession officially ends, which is why timing it is so hard.',
    example: 'In 2008 GDP fell 4.3% peak to trough and unemployment hit 10%. The S&P 500 bottomed in March 2009, months before the recession officially ended.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🌧️', investopediaSlug: 'r/recession',
  },
  'sector rotation': {
    term: 'Sector Rotation',
    headline: 'What is Sector Rotation?',
    body: 'Sector rotation is money moving between industry groups as the economic cycle shifts. Early cycle favors cyclicals like consumer discretionary and financials; late cycle favors defensives like utilities, staples, and health care. You can see it on this app when one sector runs hot on the watchlist while another stalls.',
    example: 'As rate-cut hopes rise, investors dump defensive staples and pile into semis and homebuilders. Over a month, XLK gains 9% while XLP drops 3%.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🎠',
  },

  // ── Reading charts ─────────────────────────────────────────
  'candlestick': {
    term: 'Candlestick',
    headline: 'What is a Candlestick?',
    body: 'A candlestick summarizes one period of price action using four numbers: open, high, low, and close. The thick body spans open to close; the thin wicks show the extremes. Green means it closed higher than it opened, red lower. A long lower wick says buyers stepped in.',
    example: 'A daily candle opens at $50, runs to $55, dips to $48, and closes at $54. The long lower wick shows buyers defended $48 — often read as support.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🕯️', investopediaSlug: 'c/candlestick',
  },
  'MACD': {
    term: 'MACD',
    headline: 'What is MACD?',
    body: 'MACD, short for Moving Average Convergence Divergence, compares two moving averages of price to gauge momentum. It plots a fast line, a slow signal line, and a histogram of the difference. When the fast line crosses above the slow line traders read it as bullish; below, bearish. It lags price by design.',
    example: 'MACD\'s fast line crosses above its signal line after a downtrend, and the histogram flips positive — traders treat it as an early sign momentum is turning up.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🔀', investopediaSlug: 'm/macd',
  },
  'volume analysis': {
    term: 'Volume Analysis',
    headline: 'What is Volume Analysis?',
    body: 'Volume is the number of shares traded in a period, and it measures the conviction behind a price move. A breakout on heavy volume is far more trustworthy than one on thin volume. Heavy volume on a decline signals real selling. Price tells you what happened; volume tells you how much it mattered.',
    example: 'A stock breaks above $100 resistance on three times its average daily volume — a strong signal. The same breakout on half the usual volume often fails and reverses.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🔊', investopediaSlug: 'v/volume',
  },
  'trend vs range': {
    term: 'Trend vs Range',
    headline: 'Trend vs Range: Which Regime Are You In?',
    body: 'A market is either trending — making higher highs or lower lows, moving directionally — or ranging, bouncing between a floor and a ceiling. Trend-following strategies work in trends; mean reversion works in ranges. Misreading the regime is why good strategies suddenly stop working.',
    example: 'For six months a stock chops between $40 and $45, a range. It finally breaks $45 on volume and trends to $58: the regime changed from range to trend.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '↔️',
  },
  'price gap': {
    term: 'Price Gap',
    headline: 'What is a Price Gap?',
    body: 'A price gap is a jump where a stock opens well above or below the prior close, leaving an empty space on the chart because no trades occurred in between. Gaps usually come from overnight news or earnings. Many traders treat an unfilled gap as a level price may eventually revisit.',
    example: 'A company reports blowout earnings after the close. The stock closes at $80 and opens at $90 the next morning — a $10 gap up that may later act as support.',
    level: 'Trader', category: 'Reading the Market',
    emoji: '🕳️',
  },
};
