// ═══════════════════════════════════════════════════════════════
// tests/classifier-probe.test.ts — OPT-IN gpt-5-nano accuracy probe
// ═══════════════════════════════════════════════════════════════
//
// Runs the FULL classifier (fast-path + gpt-5-nano) over the curated intent
// dataset and reports per-category agreement plus a disagreement list. NOT a
// CI test — it costs tokens and needs OPENAI_API_KEY. Opt in explicitly:
//
//   OPENAI_API_KEY=... RUN_CLASSIFIER_PROBE=1 npx vitest run tests/classifier-probe.test.ts
//
// NOTE: the dataset was generated by a second LLM, so its labels are a
// REFERENCE, not ground truth. Disagreements are reviewed by hand — they
// frequently surface the portfolio_relative_question vs scheduled_activity vs
// account_state boundary blur. The production audit (classifier_audit table +
// scripts/classifier-audit.mjs) is the authoritative continuous review.
// ═══════════════════════════════════════════════════════════════

import { describe, it, expect } from 'vitest';
import { classify } from '../lib/ai/classifier';
import dataset from './fixtures/intent-dataset.json';

type Entry = { message: string; category: string };

const run = process.env.RUN_CLASSIFIER_PROBE === '1' && !!process.env.OPENAI_API_KEY;

describe.skipIf(!run)('gpt-5-nano classifier probe (opt-in)', () => {
  it('labels the dataset and reports agreement vs the reference labels', async () => {
    const rows = dataset as Entry[];
    const byCat: Record<string, { n: number; ok: number }> = {};
    const disagreements: string[] = [];

    for (const e of rows) {
      const got = (await classify(e.message)).category;
      const want = e.category;
      byCat[want] = byCat[want] || { n: 0, ok: 0 };
      byCat[want].n++;
      if (got === want) byCat[want].ok++;
      else disagreements.push(`[${want}→${got}] "${e.message}"`);
    }

    // eslint-disable-next-line no-console
    console.log('\n=== classifier agreement by reference category ===');
    let total = 0, ok = 0;
    for (const [cat, s] of Object.entries(byCat).sort((a, b) => b[1].n - a[1].n)) {
      total += s.n; ok += s.ok;
      // eslint-disable-next-line no-console
      console.log(`  ${cat.padEnd(28)} ${s.ok}/${s.n}  (${((s.ok / s.n) * 100).toFixed(0)}%)`);
    }
    // eslint-disable-next-line no-console
    console.log(`\n  TOTAL ${ok}/${total} (${((ok / total) * 100).toFixed(1)}%)\n`);
    // eslint-disable-next-line no-console
    console.log(`=== ${disagreements.length} disagreements ===`);
    for (const m of disagreements) console.log(`  ✗ ${m}`);

    expect(ok / total).toBeGreaterThanOrEqual(0.8);
  }, 1800_000);
});
