import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase';

export async function POST(req: NextRequest) {
  try {
    const {
      email,
      password,
      first_name,
      last_name,
      investor_style,
      risk_tolerance,
      pending_choice,
      pending_connection_type,
    } = await req.json();

    // Validate required fields
    if (!email || !password) {
      return NextResponse.json(
        { error: 'Email and password required' },
        { status: 400 },
      );
    }

    const serviceClient = createServerClient();

    // Step 1: Create user via admin API (full control)
    const { data: newUser, error: createError } =
      await serviceClient.auth.admin.createUser({
        email: email.trim().toLowerCase(),
        password,
        email_confirm: false, // requires OTP verification
        user_metadata: {
          first_name,
          last_name,
          investor_style,
          risk_tolerance,
          pending_choice,
          pending_connection_type: pending_connection_type ?? null,
        },
      });

    if (createError) {
      // Handle duplicate email
      if (
        createError.message.includes('already registered') ||
        createError.message.includes('already been registered')
      ) {
        return NextResponse.json(
          { error: 'duplicate_email' },
          { status: 409 },
        );
      }

      console.error('[signup] admin.createUser error:', createError);
      return NextResponse.json(
        { error: createError.message },
        { status: 400 },
      );
    }

    console.log('[signup] user created:', newUser.user.id);

    // Step 2: Generate and send 6-digit OTP
    // auth.admin.generateLink with type 'signup' generates
    // a 6-digit token available as {{ .Token }} in the
    // "Confirm signup" email template
    const { error: otpError } = await serviceClient.auth.admin.generateLink({
      type: 'signup',
      email: email.trim().toLowerCase(),
      options: {
        data: {
          first_name,
          last_name,
          investor_style,
          risk_tolerance,
          pending_choice,
          pending_connection_type: pending_connection_type ?? null,
        },
      },
    });

    // Note: generateLink sends the email automatically via
    // Supabase's built-in email provider when configured.
    // The {{ .Token }} in the template will be the 6-digit
    // OTP generated by this call.

    if (otpError) {
      // User was created — OTP send is secondary
      console.warn('[signup] generateLink OTP error:', otpError.message);
    } else {
      console.log('[signup] OTP generated and sent');
    }

    return NextResponse.json({
      success: true,
      user_id: newUser.user.id,
    });
  } catch (err) {
    console.error('[signup] unhandled error:', err);
    return NextResponse.json(
      { error: 'Signup failed' },
      { status: 500 },
    );
  }
}
